// Code generated by ent, DO NOT EDIT.

package genclients

import (
	"context"
	"fmcam/systems/genclients/capturelogs"
	"fmcam/systems/genclients/predicate"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CaptureLogsQuery is the builder for querying CaptureLogs entities.
type CaptureLogsQuery struct {
	config
	ctx        *QueryContext
	order      []capturelogs.OrderOption
	inters     []Interceptor
	predicates []predicate.CaptureLogs
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CaptureLogsQuery builder.
func (clq *CaptureLogsQuery) Where(ps ...predicate.CaptureLogs) *CaptureLogsQuery {
	clq.predicates = append(clq.predicates, ps...)
	return clq
}

// Limit the number of records to be returned by this query.
func (clq *CaptureLogsQuery) Limit(limit int) *CaptureLogsQuery {
	clq.ctx.Limit = &limit
	return clq
}

// Offset to start from.
func (clq *CaptureLogsQuery) Offset(offset int) *CaptureLogsQuery {
	clq.ctx.Offset = &offset
	return clq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (clq *CaptureLogsQuery) Unique(unique bool) *CaptureLogsQuery {
	clq.ctx.Unique = &unique
	return clq
}

// Order specifies how the records should be ordered.
func (clq *CaptureLogsQuery) Order(o ...capturelogs.OrderOption) *CaptureLogsQuery {
	clq.order = append(clq.order, o...)
	return clq
}

// First returns the first CaptureLogs entity from the query.
// Returns a *NotFoundError when no CaptureLogs was found.
func (clq *CaptureLogsQuery) First(ctx context.Context) (*CaptureLogs, error) {
	nodes, err := clq.Limit(1).All(setContextOp(ctx, clq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{capturelogs.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (clq *CaptureLogsQuery) FirstX(ctx context.Context) *CaptureLogs {
	node, err := clq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CaptureLogs ID from the query.
// Returns a *NotFoundError when no CaptureLogs ID was found.
func (clq *CaptureLogsQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = clq.Limit(1).IDs(setContextOp(ctx, clq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{capturelogs.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (clq *CaptureLogsQuery) FirstIDX(ctx context.Context) int64 {
	id, err := clq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CaptureLogs entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CaptureLogs entity is found.
// Returns a *NotFoundError when no CaptureLogs entities are found.
func (clq *CaptureLogsQuery) Only(ctx context.Context) (*CaptureLogs, error) {
	nodes, err := clq.Limit(2).All(setContextOp(ctx, clq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{capturelogs.Label}
	default:
		return nil, &NotSingularError{capturelogs.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (clq *CaptureLogsQuery) OnlyX(ctx context.Context) *CaptureLogs {
	node, err := clq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CaptureLogs ID in the query.
// Returns a *NotSingularError when more than one CaptureLogs ID is found.
// Returns a *NotFoundError when no entities are found.
func (clq *CaptureLogsQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = clq.Limit(2).IDs(setContextOp(ctx, clq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{capturelogs.Label}
	default:
		err = &NotSingularError{capturelogs.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (clq *CaptureLogsQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := clq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CaptureLogsSlice.
func (clq *CaptureLogsQuery) All(ctx context.Context) ([]*CaptureLogs, error) {
	ctx = setContextOp(ctx, clq.ctx, ent.OpQueryAll)
	if err := clq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CaptureLogs, *CaptureLogsQuery]()
	return withInterceptors[[]*CaptureLogs](ctx, clq, qr, clq.inters)
}

// AllX is like All, but panics if an error occurs.
func (clq *CaptureLogsQuery) AllX(ctx context.Context) []*CaptureLogs {
	nodes, err := clq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CaptureLogs IDs.
func (clq *CaptureLogsQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if clq.ctx.Unique == nil && clq.path != nil {
		clq.Unique(true)
	}
	ctx = setContextOp(ctx, clq.ctx, ent.OpQueryIDs)
	if err = clq.Select(capturelogs.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (clq *CaptureLogsQuery) IDsX(ctx context.Context) []int64 {
	ids, err := clq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (clq *CaptureLogsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, clq.ctx, ent.OpQueryCount)
	if err := clq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, clq, querierCount[*CaptureLogsQuery](), clq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (clq *CaptureLogsQuery) CountX(ctx context.Context) int {
	count, err := clq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (clq *CaptureLogsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, clq.ctx, ent.OpQueryExist)
	switch _, err := clq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("genclients: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (clq *CaptureLogsQuery) ExistX(ctx context.Context) bool {
	exist, err := clq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CaptureLogsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (clq *CaptureLogsQuery) Clone() *CaptureLogsQuery {
	if clq == nil {
		return nil
	}
	return &CaptureLogsQuery{
		config:     clq.config,
		ctx:        clq.ctx.Clone(),
		order:      append([]capturelogs.OrderOption{}, clq.order...),
		inters:     append([]Interceptor{}, clq.inters...),
		predicates: append([]predicate.CaptureLogs{}, clq.predicates...),
		// clone intermediate query.
		sql:  clq.sql.Clone(),
		path: clq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID uuid.UUID `json:"tenant_id"  db:"tenant_id"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CaptureLogs.Query().
//		GroupBy(capturelogs.FieldTenantID).
//		Aggregate(genclients.Count()).
//		Scan(ctx, &v)
func (clq *CaptureLogsQuery) GroupBy(field string, fields ...string) *CaptureLogsGroupBy {
	clq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CaptureLogsGroupBy{build: clq}
	grbuild.flds = &clq.ctx.Fields
	grbuild.label = capturelogs.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID uuid.UUID `json:"tenant_id"  db:"tenant_id"`
//	}
//
//	client.CaptureLogs.Query().
//		Select(capturelogs.FieldTenantID).
//		Scan(ctx, &v)
func (clq *CaptureLogsQuery) Select(fields ...string) *CaptureLogsSelect {
	clq.ctx.Fields = append(clq.ctx.Fields, fields...)
	sbuild := &CaptureLogsSelect{CaptureLogsQuery: clq}
	sbuild.label = capturelogs.Label
	sbuild.flds, sbuild.scan = &clq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CaptureLogsSelect configured with the given aggregations.
func (clq *CaptureLogsQuery) Aggregate(fns ...AggregateFunc) *CaptureLogsSelect {
	return clq.Select().Aggregate(fns...)
}

func (clq *CaptureLogsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range clq.inters {
		if inter == nil {
			return fmt.Errorf("genclients: uninitialized interceptor (forgotten import genclients/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, clq); err != nil {
				return err
			}
		}
	}
	for _, f := range clq.ctx.Fields {
		if !capturelogs.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("genclients: invalid field %q for query", f)}
		}
	}
	if clq.path != nil {
		prev, err := clq.path(ctx)
		if err != nil {
			return err
		}
		clq.sql = prev
	}
	return nil
}

func (clq *CaptureLogsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CaptureLogs, error) {
	var (
		nodes = []*CaptureLogs{}
		_spec = clq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CaptureLogs).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CaptureLogs{config: clq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, clq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (clq *CaptureLogsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := clq.querySpec()
	_spec.Node.Columns = clq.ctx.Fields
	if len(clq.ctx.Fields) > 0 {
		_spec.Unique = clq.ctx.Unique != nil && *clq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, clq.driver, _spec)
}

func (clq *CaptureLogsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(capturelogs.Table, capturelogs.Columns, sqlgraph.NewFieldSpec(capturelogs.FieldID, field.TypeInt64))
	_spec.From = clq.sql
	if unique := clq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if clq.path != nil {
		_spec.Unique = true
	}
	if fields := clq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, capturelogs.FieldID)
		for i := range fields {
			if fields[i] != capturelogs.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := clq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := clq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := clq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := clq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (clq *CaptureLogsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(clq.driver.Dialect())
	t1 := builder.Table(capturelogs.Table)
	columns := clq.ctx.Fields
	if len(columns) == 0 {
		columns = capturelogs.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if clq.sql != nil {
		selector = clq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if clq.ctx.Unique != nil && *clq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range clq.predicates {
		p(selector)
	}
	for _, p := range clq.order {
		p(selector)
	}
	if offset := clq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := clq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CaptureLogsGroupBy is the group-by builder for CaptureLogs entities.
type CaptureLogsGroupBy struct {
	selector
	build *CaptureLogsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (clgb *CaptureLogsGroupBy) Aggregate(fns ...AggregateFunc) *CaptureLogsGroupBy {
	clgb.fns = append(clgb.fns, fns...)
	return clgb
}

// Scan applies the selector query and scans the result into the given value.
func (clgb *CaptureLogsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, clgb.build.ctx, ent.OpQueryGroupBy)
	if err := clgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CaptureLogsQuery, *CaptureLogsGroupBy](ctx, clgb.build, clgb, clgb.build.inters, v)
}

func (clgb *CaptureLogsGroupBy) sqlScan(ctx context.Context, root *CaptureLogsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(clgb.fns))
	for _, fn := range clgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*clgb.flds)+len(clgb.fns))
		for _, f := range *clgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*clgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := clgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CaptureLogsSelect is the builder for selecting fields of CaptureLogs entities.
type CaptureLogsSelect struct {
	*CaptureLogsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cls *CaptureLogsSelect) Aggregate(fns ...AggregateFunc) *CaptureLogsSelect {
	cls.fns = append(cls.fns, fns...)
	return cls
}

// Scan applies the selector query and scans the result into the given value.
func (cls *CaptureLogsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cls.ctx, ent.OpQuerySelect)
	if err := cls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CaptureLogsQuery, *CaptureLogsSelect](ctx, cls.CaptureLogsQuery, cls, cls.inters, v)
}

func (cls *CaptureLogsSelect) sqlScan(ctx context.Context, root *CaptureLogsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cls.fns))
	for _, fn := range cls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
