// Code generated by ent, DO NOT EDIT.

package genclients

import (
	"context"
	"fmcam/systems/genclients/capturelogs"
	"fmcam/systems/genclients/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CaptureLogsDelete is the builder for deleting a CaptureLogs entity.
type CaptureLogsDelete struct {
	config
	hooks    []Hook
	mutation *CaptureLogsMutation
}

// Where appends a list predicates to the CaptureLogsDelete builder.
func (cld *CaptureLogsDelete) Where(ps ...predicate.CaptureLogs) *CaptureLogsDelete {
	cld.mutation.Where(ps...)
	return cld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cld *CaptureLogsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, cld.sqlExec, cld.mutation, cld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (cld *CaptureLogsDelete) ExecX(ctx context.Context) int {
	n, err := cld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cld *CaptureLogsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(capturelogs.Table, sqlgraph.NewFieldSpec(capturelogs.FieldID, field.TypeInt64))
	if ps := cld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	cld.mutation.done = true
	return affected, err
}

// CaptureLogsDeleteOne is the builder for deleting a single CaptureLogs entity.
type CaptureLogsDeleteOne struct {
	cld *CaptureLogsDelete
}

// Where appends a list predicates to the CaptureLogsDelete builder.
func (cldo *CaptureLogsDeleteOne) Where(ps ...predicate.CaptureLogs) *CaptureLogsDeleteOne {
	cldo.cld.mutation.Where(ps...)
	return cldo
}

// Exec executes the deletion query.
func (cldo *CaptureLogsDeleteOne) Exec(ctx context.Context) error {
	n, err := cldo.cld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{capturelogs.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cldo *CaptureLogsDeleteOne) ExecX(ctx context.Context) {
	if err := cldo.Exec(ctx); err != nil {
		panic(err)
	}
}
