// Code generated by ent, DO NOT EDIT.

package genclients

import (
	"context"
	"fmcam/systems/genclients/fmalertgroup"
	"fmcam/systems/genclients/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FmAlertGroupDelete is the builder for deleting a FmAlertGroup entity.
type FmAlertGroupDelete struct {
	config
	hooks    []Hook
	mutation *FmAlertGroupMutation
}

// Where appends a list predicates to the FmAlertGroupDelete builder.
func (fagd *FmAlertGroupDelete) Where(ps ...predicate.FmAlertGroup) *FmAlertGroupDelete {
	fagd.mutation.Where(ps...)
	return fagd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (fagd *FmAlertGroupDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, fagd.sqlExec, fagd.mutation, fagd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (fagd *FmAlertGroupDelete) ExecX(ctx context.Context) int {
	n, err := fagd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (fagd *FmAlertGroupDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(fmalertgroup.Table, sqlgraph.NewFieldSpec(fmalertgroup.FieldID, field.TypeInt64))
	if ps := fagd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, fagd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	fagd.mutation.done = true
	return affected, err
}

// FmAlertGroupDeleteOne is the builder for deleting a single FmAlertGroup entity.
type FmAlertGroupDeleteOne struct {
	fagd *FmAlertGroupDelete
}

// Where appends a list predicates to the FmAlertGroupDelete builder.
func (fagdo *FmAlertGroupDeleteOne) Where(ps ...predicate.FmAlertGroup) *FmAlertGroupDeleteOne {
	fagdo.fagd.mutation.Where(ps...)
	return fagdo
}

// Exec executes the deletion query.
func (fagdo *FmAlertGroupDeleteOne) Exec(ctx context.Context) error {
	n, err := fagdo.fagd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{fmalertgroup.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (fagdo *FmAlertGroupDeleteOne) ExecX(ctx context.Context) {
	if err := fagdo.Exec(ctx); err != nil {
		panic(err)
	}
}
