// Code generated by ent, DO NOT EDIT.

package genclients

import (
	"context"
	"fmcam/systems/genclients/fmdemands"
	"fmcam/systems/genclients/predicate"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FmDemandsQuery is the builder for querying FmDemands entities.
type FmDemandsQuery struct {
	config
	ctx        *QueryContext
	order      []fmdemands.OrderOption
	inters     []Interceptor
	predicates []predicate.FmDemands
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FmDemandsQuery builder.
func (fdq *FmDemandsQuery) Where(ps ...predicate.FmDemands) *FmDemandsQuery {
	fdq.predicates = append(fdq.predicates, ps...)
	return fdq
}

// Limit the number of records to be returned by this query.
func (fdq *FmDemandsQuery) Limit(limit int) *FmDemandsQuery {
	fdq.ctx.Limit = &limit
	return fdq
}

// Offset to start from.
func (fdq *FmDemandsQuery) Offset(offset int) *FmDemandsQuery {
	fdq.ctx.Offset = &offset
	return fdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (fdq *FmDemandsQuery) Unique(unique bool) *FmDemandsQuery {
	fdq.ctx.Unique = &unique
	return fdq
}

// Order specifies how the records should be ordered.
func (fdq *FmDemandsQuery) Order(o ...fmdemands.OrderOption) *FmDemandsQuery {
	fdq.order = append(fdq.order, o...)
	return fdq
}

// First returns the first FmDemands entity from the query.
// Returns a *NotFoundError when no FmDemands was found.
func (fdq *FmDemandsQuery) First(ctx context.Context) (*FmDemands, error) {
	nodes, err := fdq.Limit(1).All(setContextOp(ctx, fdq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{fmdemands.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fdq *FmDemandsQuery) FirstX(ctx context.Context) *FmDemands {
	node, err := fdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FmDemands ID from the query.
// Returns a *NotFoundError when no FmDemands ID was found.
func (fdq *FmDemandsQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = fdq.Limit(1).IDs(setContextOp(ctx, fdq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{fmdemands.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fdq *FmDemandsQuery) FirstIDX(ctx context.Context) int64 {
	id, err := fdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FmDemands entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FmDemands entity is found.
// Returns a *NotFoundError when no FmDemands entities are found.
func (fdq *FmDemandsQuery) Only(ctx context.Context) (*FmDemands, error) {
	nodes, err := fdq.Limit(2).All(setContextOp(ctx, fdq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{fmdemands.Label}
	default:
		return nil, &NotSingularError{fmdemands.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fdq *FmDemandsQuery) OnlyX(ctx context.Context) *FmDemands {
	node, err := fdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FmDemands ID in the query.
// Returns a *NotSingularError when more than one FmDemands ID is found.
// Returns a *NotFoundError when no entities are found.
func (fdq *FmDemandsQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = fdq.Limit(2).IDs(setContextOp(ctx, fdq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{fmdemands.Label}
	default:
		err = &NotSingularError{fmdemands.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fdq *FmDemandsQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := fdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FmDemandsSlice.
func (fdq *FmDemandsQuery) All(ctx context.Context) ([]*FmDemands, error) {
	ctx = setContextOp(ctx, fdq.ctx, ent.OpQueryAll)
	if err := fdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FmDemands, *FmDemandsQuery]()
	return withInterceptors[[]*FmDemands](ctx, fdq, qr, fdq.inters)
}

// AllX is like All, but panics if an error occurs.
func (fdq *FmDemandsQuery) AllX(ctx context.Context) []*FmDemands {
	nodes, err := fdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FmDemands IDs.
func (fdq *FmDemandsQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if fdq.ctx.Unique == nil && fdq.path != nil {
		fdq.Unique(true)
	}
	ctx = setContextOp(ctx, fdq.ctx, ent.OpQueryIDs)
	if err = fdq.Select(fmdemands.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fdq *FmDemandsQuery) IDsX(ctx context.Context) []int64 {
	ids, err := fdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fdq *FmDemandsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, fdq.ctx, ent.OpQueryCount)
	if err := fdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, fdq, querierCount[*FmDemandsQuery](), fdq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (fdq *FmDemandsQuery) CountX(ctx context.Context) int {
	count, err := fdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fdq *FmDemandsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, fdq.ctx, ent.OpQueryExist)
	switch _, err := fdq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("genclients: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (fdq *FmDemandsQuery) ExistX(ctx context.Context) bool {
	exist, err := fdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FmDemandsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fdq *FmDemandsQuery) Clone() *FmDemandsQuery {
	if fdq == nil {
		return nil
	}
	return &FmDemandsQuery{
		config:     fdq.config,
		ctx:        fdq.ctx.Clone(),
		order:      append([]fmdemands.OrderOption{}, fdq.order...),
		inters:     append([]Interceptor{}, fdq.inters...),
		predicates: append([]predicate.FmDemands{}, fdq.predicates...),
		// clone intermediate query.
		sql:  fdq.sql.Clone(),
		path: fdq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Supplier string `json:"supplier"  db:"supplier"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FmDemands.Query().
//		GroupBy(fmdemands.FieldSupplier).
//		Aggregate(genclients.Count()).
//		Scan(ctx, &v)
func (fdq *FmDemandsQuery) GroupBy(field string, fields ...string) *FmDemandsGroupBy {
	fdq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FmDemandsGroupBy{build: fdq}
	grbuild.flds = &fdq.ctx.Fields
	grbuild.label = fmdemands.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Supplier string `json:"supplier"  db:"supplier"`
//	}
//
//	client.FmDemands.Query().
//		Select(fmdemands.FieldSupplier).
//		Scan(ctx, &v)
func (fdq *FmDemandsQuery) Select(fields ...string) *FmDemandsSelect {
	fdq.ctx.Fields = append(fdq.ctx.Fields, fields...)
	sbuild := &FmDemandsSelect{FmDemandsQuery: fdq}
	sbuild.label = fmdemands.Label
	sbuild.flds, sbuild.scan = &fdq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FmDemandsSelect configured with the given aggregations.
func (fdq *FmDemandsQuery) Aggregate(fns ...AggregateFunc) *FmDemandsSelect {
	return fdq.Select().Aggregate(fns...)
}

func (fdq *FmDemandsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range fdq.inters {
		if inter == nil {
			return fmt.Errorf("genclients: uninitialized interceptor (forgotten import genclients/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, fdq); err != nil {
				return err
			}
		}
	}
	for _, f := range fdq.ctx.Fields {
		if !fmdemands.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("genclients: invalid field %q for query", f)}
		}
	}
	if fdq.path != nil {
		prev, err := fdq.path(ctx)
		if err != nil {
			return err
		}
		fdq.sql = prev
	}
	return nil
}

func (fdq *FmDemandsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FmDemands, error) {
	var (
		nodes = []*FmDemands{}
		_spec = fdq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FmDemands).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FmDemands{config: fdq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, fdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (fdq *FmDemandsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := fdq.querySpec()
	_spec.Node.Columns = fdq.ctx.Fields
	if len(fdq.ctx.Fields) > 0 {
		_spec.Unique = fdq.ctx.Unique != nil && *fdq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, fdq.driver, _spec)
}

func (fdq *FmDemandsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(fmdemands.Table, fmdemands.Columns, sqlgraph.NewFieldSpec(fmdemands.FieldID, field.TypeInt64))
	_spec.From = fdq.sql
	if unique := fdq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if fdq.path != nil {
		_spec.Unique = true
	}
	if fields := fdq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fmdemands.FieldID)
		for i := range fields {
			if fields[i] != fmdemands.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := fdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fdq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fdq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (fdq *FmDemandsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(fdq.driver.Dialect())
	t1 := builder.Table(fmdemands.Table)
	columns := fdq.ctx.Fields
	if len(columns) == 0 {
		columns = fmdemands.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if fdq.sql != nil {
		selector = fdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if fdq.ctx.Unique != nil && *fdq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range fdq.predicates {
		p(selector)
	}
	for _, p := range fdq.order {
		p(selector)
	}
	if offset := fdq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fdq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FmDemandsGroupBy is the group-by builder for FmDemands entities.
type FmDemandsGroupBy struct {
	selector
	build *FmDemandsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fdgb *FmDemandsGroupBy) Aggregate(fns ...AggregateFunc) *FmDemandsGroupBy {
	fdgb.fns = append(fdgb.fns, fns...)
	return fdgb
}

// Scan applies the selector query and scans the result into the given value.
func (fdgb *FmDemandsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fdgb.build.ctx, ent.OpQueryGroupBy)
	if err := fdgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FmDemandsQuery, *FmDemandsGroupBy](ctx, fdgb.build, fdgb, fdgb.build.inters, v)
}

func (fdgb *FmDemandsGroupBy) sqlScan(ctx context.Context, root *FmDemandsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(fdgb.fns))
	for _, fn := range fdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*fdgb.flds)+len(fdgb.fns))
		for _, f := range *fdgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*fdgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fdgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FmDemandsSelect is the builder for selecting fields of FmDemands entities.
type FmDemandsSelect struct {
	*FmDemandsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fds *FmDemandsSelect) Aggregate(fns ...AggregateFunc) *FmDemandsSelect {
	fds.fns = append(fds.fns, fns...)
	return fds
}

// Scan applies the selector query and scans the result into the given value.
func (fds *FmDemandsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fds.ctx, ent.OpQuerySelect)
	if err := fds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FmDemandsQuery, *FmDemandsSelect](ctx, fds.FmDemandsQuery, fds, fds.inters, v)
}

func (fds *FmDemandsSelect) sqlScan(ctx context.Context, root *FmDemandsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fds.fns))
	for _, fn := range fds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
