// Code generated by ent, DO NOT EDIT.

package genclients

import (
	"context"
	"fmcam/systems/genclients/fmpmsapi"
	"fmcam/systems/genclients/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FMPMSApiDelete is the builder for deleting a FMPMSApi entity.
type FMPMSApiDelete struct {
	config
	hooks    []Hook
	mutation *FMPMSApiMutation
}

// Where appends a list predicates to the FMPMSApiDelete builder.
func (fad *FMPMSApiDelete) Where(ps ...predicate.FMPMSApi) *FMPMSApiDelete {
	fad.mutation.Where(ps...)
	return fad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (fad *FMPMSApiDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, fad.sqlExec, fad.mutation, fad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (fad *FMPMSApiDelete) ExecX(ctx context.Context) int {
	n, err := fad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (fad *FMPMSApiDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(fmpmsapi.Table, sqlgraph.NewFieldSpec(fmpmsapi.FieldID, field.TypeInt64))
	if ps := fad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, fad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	fad.mutation.done = true
	return affected, err
}

// FMPMSApiDeleteOne is the builder for deleting a single FMPMSApi entity.
type FMPMSApiDeleteOne struct {
	fad *FMPMSApiDelete
}

// Where appends a list predicates to the FMPMSApiDelete builder.
func (fado *FMPMSApiDeleteOne) Where(ps ...predicate.FMPMSApi) *FMPMSApiDeleteOne {
	fado.fad.mutation.Where(ps...)
	return fado
}

// Exec executes the deletion query.
func (fado *FMPMSApiDeleteOne) Exec(ctx context.Context) error {
	n, err := fado.fad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{fmpmsapi.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (fado *FMPMSApiDeleteOne) ExecX(ctx context.Context) {
	if err := fado.Exec(ctx); err != nil {
		panic(err)
	}
}
