// Code generated by ent, DO NOT EDIT.

package genclients

import (
	"context"
	"fmcam/systems/genclients/govcity"
	"fmcam/systems/genclients/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GovCityDelete is the builder for deleting a GovCity entity.
type GovCityDelete struct {
	config
	hooks    []Hook
	mutation *GovCityMutation
}

// Where appends a list predicates to the GovCityDelete builder.
func (gcd *GovCityDelete) Where(ps ...predicate.GovCity) *GovCityDelete {
	gcd.mutation.Where(ps...)
	return gcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (gcd *GovCityDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, gcd.sqlExec, gcd.mutation, gcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (gcd *GovCityDelete) ExecX(ctx context.Context) int {
	n, err := gcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (gcd *GovCityDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(govcity.Table, sqlgraph.NewFieldSpec(govcity.FieldID, field.TypeInt64))
	if ps := gcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, gcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	gcd.mutation.done = true
	return affected, err
}

// GovCityDeleteOne is the builder for deleting a single GovCity entity.
type GovCityDeleteOne struct {
	gcd *GovCityDelete
}

// Where appends a list predicates to the GovCityDelete builder.
func (gcdo *GovCityDeleteOne) Where(ps ...predicate.GovCity) *GovCityDeleteOne {
	gcdo.gcd.mutation.Where(ps...)
	return gcdo
}

// Exec executes the deletion query.
func (gcdo *GovCityDeleteOne) Exec(ctx context.Context) error {
	n, err := gcdo.gcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{govcity.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (gcdo *GovCityDeleteOne) ExecX(ctx context.Context) {
	if err := gcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
