// Code generated by ent, DO NOT EDIT.

package genclients

import (
	"context"
	"errors"
	"fmcam/systems/genclients/province"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProvinceCreate is the builder for creating a Province entity.
type ProvinceCreate struct {
	config
	mutation *ProvinceMutation
	hooks    []Hook
}

// SetCode sets the "code" field.
func (pc *ProvinceCreate) SetCode(s string) *ProvinceCreate {
	pc.mutation.SetCode(s)
	return pc
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (pc *ProvinceCreate) SetNillableCode(s *string) *ProvinceCreate {
	if s != nil {
		pc.SetCode(*s)
	}
	return pc
}

// SetName sets the "name" field.
func (pc *ProvinceCreate) SetName(s string) *ProvinceCreate {
	pc.mutation.SetName(s)
	return pc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (pc *ProvinceCreate) SetNillableName(s *string) *ProvinceCreate {
	if s != nil {
		pc.SetName(*s)
	}
	return pc
}

// SetCreator sets the "creator" field.
func (pc *ProvinceCreate) SetCreator(s string) *ProvinceCreate {
	pc.mutation.SetCreator(s)
	return pc
}

// SetNillableCreator sets the "creator" field if the given value is not nil.
func (pc *ProvinceCreate) SetNillableCreator(s *string) *ProvinceCreate {
	if s != nil {
		pc.SetCreator(*s)
	}
	return pc
}

// SetDeleteFlag sets the "delete_flag" field.
func (pc *ProvinceCreate) SetDeleteFlag(s string) *ProvinceCreate {
	pc.mutation.SetDeleteFlag(s)
	return pc
}

// SetNillableDeleteFlag sets the "delete_flag" field if the given value is not nil.
func (pc *ProvinceCreate) SetNillableDeleteFlag(s *string) *ProvinceCreate {
	if s != nil {
		pc.SetDeleteFlag(*s)
	}
	return pc
}

// SetCreatedTime sets the "created_time" field.
func (pc *ProvinceCreate) SetCreatedTime(t time.Time) *ProvinceCreate {
	pc.mutation.SetCreatedTime(t)
	return pc
}

// SetNillableCreatedTime sets the "created_time" field if the given value is not nil.
func (pc *ProvinceCreate) SetNillableCreatedTime(t *time.Time) *ProvinceCreate {
	if t != nil {
		pc.SetCreatedTime(*t)
	}
	return pc
}

// SetID sets the "id" field.
func (pc *ProvinceCreate) SetID(i int64) *ProvinceCreate {
	pc.mutation.SetID(i)
	return pc
}

// Mutation returns the ProvinceMutation object of the builder.
func (pc *ProvinceCreate) Mutation() *ProvinceMutation {
	return pc.mutation
}

// Save creates the Province in the database.
func (pc *ProvinceCreate) Save(ctx context.Context) (*Province, error) {
	pc.defaults()
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *ProvinceCreate) SaveX(ctx context.Context) *Province {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *ProvinceCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *ProvinceCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pc *ProvinceCreate) defaults() {
	if _, ok := pc.mutation.Code(); !ok {
		v := province.DefaultCode
		pc.mutation.SetCode(v)
	}
	if _, ok := pc.mutation.Name(); !ok {
		v := province.DefaultName
		pc.mutation.SetName(v)
	}
	if _, ok := pc.mutation.Creator(); !ok {
		v := province.DefaultCreator
		pc.mutation.SetCreator(v)
	}
	if _, ok := pc.mutation.DeleteFlag(); !ok {
		v := province.DefaultDeleteFlag
		pc.mutation.SetDeleteFlag(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *ProvinceCreate) check() error {
	if _, ok := pc.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`genclients: missing required field "Province.code"`)}
	}
	if v, ok := pc.mutation.Code(); ok {
		if err := province.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`genclients: validator failed for field "Province.code": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`genclients: missing required field "Province.name"`)}
	}
	if v, ok := pc.mutation.Name(); ok {
		if err := province.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`genclients: validator failed for field "Province.name": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Creator(); !ok {
		return &ValidationError{Name: "creator", err: errors.New(`genclients: missing required field "Province.creator"`)}
	}
	if v, ok := pc.mutation.Creator(); ok {
		if err := province.CreatorValidator(v); err != nil {
			return &ValidationError{Name: "creator", err: fmt.Errorf(`genclients: validator failed for field "Province.creator": %w`, err)}
		}
	}
	if _, ok := pc.mutation.DeleteFlag(); !ok {
		return &ValidationError{Name: "delete_flag", err: errors.New(`genclients: missing required field "Province.delete_flag"`)}
	}
	if v, ok := pc.mutation.DeleteFlag(); ok {
		if err := province.DeleteFlagValidator(v); err != nil {
			return &ValidationError{Name: "delete_flag", err: fmt.Errorf(`genclients: validator failed for field "Province.delete_flag": %w`, err)}
		}
	}
	return nil
}

func (pc *ProvinceCreate) sqlSave(ctx context.Context) (*Province, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *ProvinceCreate) createSpec() (*Province, *sqlgraph.CreateSpec) {
	var (
		_node = &Province{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(province.Table, sqlgraph.NewFieldSpec(province.FieldID, field.TypeInt64))
	)
	if id, ok := pc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := pc.mutation.Code(); ok {
		_spec.SetField(province.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := pc.mutation.Name(); ok {
		_spec.SetField(province.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := pc.mutation.Creator(); ok {
		_spec.SetField(province.FieldCreator, field.TypeString, value)
		_node.Creator = value
	}
	if value, ok := pc.mutation.DeleteFlag(); ok {
		_spec.SetField(province.FieldDeleteFlag, field.TypeString, value)
		_node.DeleteFlag = value
	}
	if value, ok := pc.mutation.CreatedTime(); ok {
		_spec.SetField(province.FieldCreatedTime, field.TypeTime, value)
		_node.CreatedTime = &value
	}
	return _node, _spec
}

// ProvinceCreateBulk is the builder for creating many Province entities in bulk.
type ProvinceCreateBulk struct {
	config
	err      error
	builders []*ProvinceCreate
}

// Save creates the Province entities in the database.
func (pcb *ProvinceCreateBulk) Save(ctx context.Context) ([]*Province, error) {
	if pcb.err != nil {
		return nil, pcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Province, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProvinceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *ProvinceCreateBulk) SaveX(ctx context.Context) []*Province {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *ProvinceCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *ProvinceCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
